# Generated by Django 4.0.2 on 2022-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
