# Generated by Django 4.0.2 on 2022-10-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_remove_manufacturer_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
