# Generated by Django 4.0.2 on 2022-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_alter_manufacturer_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/cars'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/drivers/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/manufacturers/'),
        ),
    ]
