# Generated by Django 4.0.2 on 2022-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_alter_car_picture_url_alter_driver_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture_url',
            field=models.ImageField(null=True, upload_to='img/cars'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture_url',
            field=models.ImageField(null=True, upload_to='img/drivers/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='picture_url',
            field=models.ImageField(null=True, upload_to='img/manufacturers/'),
        ),
    ]
